/**
 * `.gobbi/project-config.json` — schema, loader, and init helper.
 *
 * One per-repo configuration file, checked into git, governing verification
 * commands and cost-table resolution for the v0.5.0 workflow. Schema is
 * validated by ajv; defaults are hydrated in TS via `deepMerge` rather than
 * ajv's `useDefaults` — see PR E §E.5 research `e5-ajv-useDefaults-pitfalls.md`
 * (ajv issue #1710 makes nested-defaults hydration fragile, so we gate with
 * ajv and merge with TS code).
 *
 * ## Resolution policy
 *
 *   - Loader uses the explicit `repoRoot` argument (tests pass a tmpdir; the
 *     CLI resolves `getRepoRoot()` once at the call site).
 *   - No walk-up search — a missing file is either auto-created by
 *     {@link ensureProjectConfig} on init, or treated as in-memory defaults by
 *     {@link loadProjectConfig} for non-init callers.
 *
 * ## Idempotency
 *
 * {@link ensureProjectConfig} is safe to call on every `gobbi workflow init`
 * invocation (startup / resume / compact hook re-entry). If the file already
 * exists it returns `{ created: false }` without touching disk or writing to
 * stderr — matching the "silent no-op" contract of the surrounding init
 * command.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import Ajv2020, { type JSONSchemaType } from 'ajv/dist/2020.js';

import { isRecord } from './guards.js';
import type { VerificationPolicy } from '../workflow/events/verification.js';

export type { VerificationPolicy };

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/** One verification command slot (lint, test, typecheck, build, format, custom). */
export interface CommandSlot {
  readonly command: string;
  readonly policy: VerificationPolicy;
  readonly timeoutMs: number;
}

/** Map of known verification command keys. `custom` may be null to disable. */
export interface VerificationCommands {
  readonly lint: CommandSlot | null;
  readonly test: CommandSlot | null;
  readonly typecheck: CommandSlot | null;
  readonly build: CommandSlot | null;
  readonly format: CommandSlot | null;
  readonly custom: CommandSlot | null;
}

export interface VerificationConfig {
  readonly commands: VerificationCommands;
  /** Ordered list of command keys (e.g. `['typecheck','test']`) to dispatch after a subagent stops. */
  readonly runAfterSubagentStop: readonly string[];
}

export interface CostConfig {
  /** `'builtin'` uses the bundled rate table; any other string is treated as a file path. */
  readonly rateTable: string;
}

/**
 * Fully-populated project config — what {@link loadProjectConfig} returns.
 * Every nested field has a value; there are no optional slots at this level.
 */
export interface ProjectConfig {
  readonly version: 1;
  readonly verification: VerificationConfig;
  readonly cost: CostConfig;
}

/**
 * On-disk shape of `.gobbi/project-config.json`. Users may omit any field
 * except `version`; {@link deepMerge} fills the rest from {@link DEFAULT_CONFIG}.
 *
 * `undefined` (i.e. property omitted in JSON) is how missing fields surface
 * after `JSON.parse`; the schema accepts the omission and the merge step
 * supplies the default. ajv's `nullable: true` handles the `custom: null`
 * case inside `verification.commands`.
 */
export interface ProjectConfigInput {
  readonly version: 1;
  readonly verification?: {
    readonly commands?: {
      readonly lint?: CommandSlot | null;
      readonly test?: CommandSlot | null;
      readonly typecheck?: CommandSlot | null;
      readonly build?: CommandSlot | null;
      readonly format?: CommandSlot | null;
      readonly custom?: CommandSlot | null;
    };
    readonly runAfterSubagentStop?: readonly string[];
  };
  readonly cost?: {
    readonly rateTable?: string;
  };
}

// ---------------------------------------------------------------------------
// Defaults — the single source of truth
// ---------------------------------------------------------------------------

export const DEFAULT_CONFIG: ProjectConfig = {
  version: 1,
  verification: {
    commands: {
      lint:      { command: 'bun lint',             policy: 'inform', timeoutMs: 60000 },
      test:      { command: 'bun test',             policy: 'gate',   timeoutMs: 300000 },
      typecheck: { command: 'bunx tsc --noEmit',    policy: 'gate',   timeoutMs: 120000 },
      build:     { command: 'bun run build',        policy: 'inform', timeoutMs: 300000 },
      format:    { command: 'bun run format:check', policy: 'inform', timeoutMs: 30000 },
      custom:    null,
    },
    runAfterSubagentStop: ['typecheck', 'test'],
  },
  cost: { rateTable: 'builtin' },
};

const GITIGNORE_CONTENT =
  '# Auto-generated by gobbi. Runtime session/worktree state.\n' +
  'sessions/\n' +
  'worktrees/\n' +
  'project/note/\n';

// ---------------------------------------------------------------------------
// JSON Schema — validation gate (NOT defaults hydration)
// ---------------------------------------------------------------------------

const commandSlotSchema = {
  type: 'object',
  required: ['command', 'policy', 'timeoutMs'],
  additionalProperties: false,
  properties: {
    command: { type: 'string', minLength: 1 },
    policy: { type: 'string', enum: ['inform', 'gate'] },
    timeoutMs: { type: 'integer', minimum: 0 },
  },
  nullable: true,
} as const;

/**
 * Top-level JSON Schema for `.gobbi/project-config.json`.
 *
 * Drift check: `JSONSchemaType<ProjectConfigInput>` forces this schema and
 * the TS interface to evolve together — `tsc --noEmit` fails on divergence.
 *
 * No `useDefaults` — defaults are provided by TS via {@link deepMerge}. See
 * `e5-ajv-useDefaults-pitfalls.md` for why nested-defaults are unreliable
 * under ajv (issue #1710 and friends).
 */
const projectConfigSchema: JSONSchemaType<ProjectConfigInput> = {
  type: 'object',
  required: ['version'],
  additionalProperties: false,
  properties: {
    version: { type: 'integer', const: 1 },
    verification: {
      type: 'object',
      nullable: true,
      additionalProperties: false,
      properties: {
        commands: {
          type: 'object',
          nullable: true,
          additionalProperties: false,
          properties: {
            lint: commandSlotSchema,
            test: commandSlotSchema,
            typecheck: commandSlotSchema,
            build: commandSlotSchema,
            format: commandSlotSchema,
            custom: commandSlotSchema,
          },
        },
        runAfterSubagentStop: {
          type: 'array',
          nullable: true,
          items: { type: 'string', minLength: 1 },
        },
      },
    },
    cost: {
      type: 'object',
      nullable: true,
      additionalProperties: false,
      properties: {
        rateTable: { type: 'string', nullable: true, minLength: 1 },
      },
    },
  },
};

const ajv = new Ajv2020({
  strict: true,
  allErrors: true,
});

const validateProjectConfig = ajv.compile<ProjectConfigInput>(projectConfigSchema);

// ---------------------------------------------------------------------------
// deepMerge — TS-side defaults hydration
// ---------------------------------------------------------------------------

/**
 * Deep-merge two plain-object trees. Right wins on leaves; arrays replace
 * (no concat); `null` on the right is a leaf and replaces the left value;
 * non-record values stop recursion.
 *
 * Only intended for {@link ProjectConfig}-shaped trees — the return type is
 * cast to the template `T` after the merge completes.
 */
export function deepMerge<T>(base: T, overlay: unknown): T {
  if (!isRecord(base) || !isRecord(overlay)) {
    // Non-object base (shouldn't happen for our use) or overlay missing —
    // return base unchanged when overlay isn't a record.
    return base;
  }

  const out: Record<string, unknown> = { ...base };
  for (const key of Object.keys(overlay)) {
    const overlayValue = overlay[key];
    const baseValue = out[key];

    if (overlayValue === undefined) continue;

    if (isRecord(baseValue) && isRecord(overlayValue)) {
      out[key] = deepMerge(baseValue, overlayValue);
    } else {
      // Leaf write: primitives, null, arrays (replace), or overlay-added keys.
      out[key] = overlayValue;
    }
  }
  return out as T;
}

// ---------------------------------------------------------------------------
// Loader + init
// ---------------------------------------------------------------------------

function configPathFor(repoRoot: string): string {
  return path.join(repoRoot, '.gobbi', 'project-config.json');
}

function gitignorePathFor(repoRoot: string): string {
  return path.join(repoRoot, '.gobbi', '.gitignore');
}

/**
 * Load and validate `.gobbi/project-config.json`, merging over
 * {@link DEFAULT_CONFIG} for a fully-populated result.
 *
 * Missing file → returns {@link DEFAULT_CONFIG} in-memory (non-init callers
 * that run before any `gobbi workflow init` should still get sane defaults).
 * Invalid JSON or schema violation → throws with the ajv error path included
 * in the message.
 */
export function loadProjectConfig(repoRoot: string): ProjectConfig {
  const configPath = configPathFor(repoRoot);
  if (!existsSync(configPath)) return DEFAULT_CONFIG;

  const raw = readFileSync(configPath, 'utf8');
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(
      `Invalid .gobbi/project-config.json: JSON parse error — ${message}`,
    );
  }

  if (!validateProjectConfig(parsed)) {
    const errors = validateProjectConfig.errors ?? [];
    const messages = errors
      .map((e) => `  ${e.instancePath || '<root>'}: ${e.message ?? 'unknown error'}`)
      .join('\n');
    throw new Error(`Invalid .gobbi/project-config.json:\n${messages}`);
  }

  return deepMerge(DEFAULT_CONFIG, parsed);
}

export interface EnsureProjectConfigResult {
  readonly created: boolean;
  readonly path: string;
}

/**
 * Create `.gobbi/project-config.json` (+ sibling `.gitignore`) if either is
 * missing. Returns `created: true` when the config file did not exist and
 * was written. Silent on stderr in the already-exists case — matches the
 * idempotency contract of `gobbi workflow init`.
 */
export function ensureProjectConfig(repoRoot: string): EnsureProjectConfigResult {
  const configPath = configPathFor(repoRoot);
  const gitignorePath = gitignorePathFor(repoRoot);

  if (existsSync(configPath)) {
    // Silent no-op. The sibling `.gitignore` is also left alone — if the
    // operator customised it we don't clobber their version.
    return { created: false, path: configPath };
  }

  mkdirSync(path.dirname(configPath), { recursive: true });
  writeFileSync(configPath, `${JSON.stringify(DEFAULT_CONFIG, null, 2)}\n`, 'utf8');

  // Create the runtime-state `.gitignore` only if it's missing. Operator
  // edits survive subsequent init invocations.
  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, GITIGNORE_CONTENT, 'utf8');
  }

  process.stderr.write('created .gobbi/project-config.json with defaults\n');
  return { created: true, path: configPath };
}
