/**
 * SQLite event store — typed wrapper around bun:sqlite.
 *
 * All methods are synchronous (bun:sqlite is a synchronous API).
 * Uses WAL mode, cached prepared statements via db.query(), and
 * ON CONFLICT(idempotency_key) DO NOTHING RETURNING * for atomic dedup.
 */

import { Database } from 'bun:sqlite';
import { CURRENT_SCHEMA_VERSION } from './migrations.js';
import type { EventRow } from './migrations.js';

// Re-export EventRow for consumers that import from store
export type { EventRow } from './migrations.js';

// ---------------------------------------------------------------------------
// Append input types
// ---------------------------------------------------------------------------

/**
 * Idempotency key formula selector.
 *
 * - 'tool-call': `${sessionId}:${toolCallId}:${eventType}` — for events
 *   triggered by tool calls (guard, delegation).
 * - 'system': `${sessionId}:${timestampMs}:${eventType}` — for events
 *   generated by the system (heartbeat, timeout).
 */
export type IdempotencyKind = 'tool-call' | 'system';

/** Input for appending an event — excludes seq (auto-assigned) and idempotency_key (computed). */
export interface AppendInput {
  readonly ts: string;
  readonly type: string;
  readonly step?: string | null | undefined;
  readonly data?: string | undefined;
  readonly actor: string;
  readonly parent_seq?: number | null | undefined;
  readonly idempotencyKind: IdempotencyKind;
  /** Required for tool-call idempotency. */
  readonly toolCallId?: string | undefined;
  /** Required for both formulas — identifies the session. */
  readonly sessionId: string;
}

// ---------------------------------------------------------------------------
// SQLite binding type — compatible with bun:sqlite's SQLQueryBindings
// ---------------------------------------------------------------------------

type SqlBindings = Record<string, string | number | bigint | boolean | null>;

// ---------------------------------------------------------------------------
// SQL statements
// ---------------------------------------------------------------------------

const SQL_CREATE_TABLE = `
CREATE TABLE IF NOT EXISTS events (
  seq INTEGER PRIMARY KEY,
  ts TEXT NOT NULL,
  schema_version INTEGER NOT NULL,
  type TEXT NOT NULL,
  step TEXT,
  data TEXT NOT NULL DEFAULT '{}',
  actor TEXT NOT NULL,
  parent_seq INTEGER REFERENCES events(seq),
  idempotency_key TEXT NOT NULL UNIQUE
)`;

const SQL_CREATE_INDEX_TYPE = `
CREATE INDEX IF NOT EXISTS idx_events_type ON events(type)`;

const SQL_CREATE_INDEX_STEP_TYPE = `
CREATE INDEX IF NOT EXISTS idx_events_step_type ON events(step, type)`;

const SQL_APPEND = `
INSERT INTO events (ts, schema_version, type, step, data, actor, parent_seq, idempotency_key)
VALUES ($ts, $schema_version, $type, $step, $data, $actor, $parent_seq, $idempotency_key)
ON CONFLICT(idempotency_key) DO NOTHING
RETURNING *`;

const SQL_REPLAY_ALL = `SELECT * FROM events ORDER BY seq ASC`;

const SQL_BY_TYPE = `SELECT * FROM events WHERE type = $type ORDER BY seq ASC`;

const SQL_BY_STEP = `SELECT * FROM events WHERE step = $step ORDER BY seq ASC`;

const SQL_BY_STEP_TYPE = `SELECT * FROM events WHERE step = $step AND type = $type ORDER BY seq ASC`;

const SQL_SINCE = `SELECT * FROM events WHERE seq > $seq ORDER BY seq ASC`;

const SQL_LAST = `SELECT * FROM events WHERE type = $type ORDER BY seq DESC LIMIT 1`;

const SQL_COUNT = `SELECT count(*) as cnt FROM events`;

// ---------------------------------------------------------------------------
// EventStore class
// ---------------------------------------------------------------------------

export class EventStore {
  private readonly db: Database;

  // Cached prepared statements — db.query() returns cached compiled bytecode.
  // Using SqlBindings as the param type to satisfy bun-types' SQLQueryBindings
  // constraint (requires index signature that named interfaces lack).
  private readonly stmtAppend;
  private readonly stmtReplayAll;
  private readonly stmtByType;
  private readonly stmtByStep;
  private readonly stmtByStepType;
  private readonly stmtSince;
  private readonly stmtLast;
  private readonly stmtCount;

  constructor(pathOrMemory: string) {
    this.db = new Database(pathOrMemory, { strict: true });
    this.db.run('PRAGMA journal_mode = WAL');
    this.db.run('PRAGMA synchronous = NORMAL');
    this.db.run('PRAGMA foreign_keys = ON');
    this.db.run('PRAGMA busy_timeout = 5000');
    this.initSchema();

    // Cache all prepared statements with typed return values
    this.stmtAppend = this.db.query<EventRow, [SqlBindings]>(SQL_APPEND);
    this.stmtReplayAll = this.db.query<EventRow, []>(SQL_REPLAY_ALL);
    this.stmtByType = this.db.query<EventRow, [SqlBindings]>(SQL_BY_TYPE);
    this.stmtByStep = this.db.query<EventRow, [SqlBindings]>(SQL_BY_STEP);
    this.stmtByStepType = this.db.query<EventRow, [SqlBindings]>(SQL_BY_STEP_TYPE);
    this.stmtSince = this.db.query<EventRow, [SqlBindings]>(SQL_SINCE);
    this.stmtLast = this.db.query<EventRow, [SqlBindings]>(SQL_LAST);
    this.stmtCount = this.db.query<{ cnt: number }, []>(SQL_COUNT);
  }

  // -------------------------------------------------------------------------
  // Schema initialization
  // -------------------------------------------------------------------------

  private initSchema(): void {
    this.db.run(SQL_CREATE_TABLE);
    this.db.run(SQL_CREATE_INDEX_TYPE);
    this.db.run(SQL_CREATE_INDEX_STEP_TYPE);
  }

  // -------------------------------------------------------------------------
  // Idempotency key computation
  // -------------------------------------------------------------------------

  private static computeIdempotencyKey(input: AppendInput): string {
    if (input.idempotencyKind === 'tool-call') {
      if (input.toolCallId === undefined) {
        throw new Error(
          'toolCallId is required for tool-call idempotency kind',
        );
      }
      return `${input.sessionId}:${input.toolCallId}:${input.type}`;
    }
    // system events use timestamp-based key
    const timestampMs = Date.parse(input.ts);
    return `${input.sessionId}:${timestampMs}:${input.type}`;
  }

  // -------------------------------------------------------------------------
  // Write operations
  // -------------------------------------------------------------------------

  /**
   * Append an event to the store.
   *
   * Returns the persisted EventRow with assigned seq, or null if the event
   * was deduplicated (idempotency key already exists).
   *
   * Uses ON CONFLICT(idempotency_key) DO NOTHING RETURNING * — other
   * constraint violations (NOT NULL, FK) still throw.
   */
  append(input: AppendInput): EventRow | null {
    const idempotencyKey = EventStore.computeIdempotencyKey(input);
    // With strict: true, bun:sqlite binds by name WITHOUT the $ prefix
    const params: SqlBindings = {
      ts: input.ts,
      schema_version: CURRENT_SCHEMA_VERSION,
      type: input.type,
      step: input.step ?? null,
      data: input.data ?? '{}',
      actor: input.actor,
      parent_seq: input.parent_seq ?? null,
      idempotency_key: idempotencyKey,
    };
    return this.stmtAppend.get(params);
  }

  /**
   * Wrap a function in a SQLite transaction with IMMEDIATE locking.
   *
   * Acquires a RESERVED lock at BEGIN, failing fast on contention rather
   * than mid-transaction. Nested calls become SAVEPOINTs automatically.
   */
  transaction<T>(fn: () => T): T {
    return this.db.transaction(fn).immediate();
  }

  // -------------------------------------------------------------------------
  // Read operations
  // -------------------------------------------------------------------------

  /** Replay all events ordered by seq ASC. */
  replayAll(): EventRow[] {
    return this.stmtReplayAll.all();
  }

  /** Return events filtered by type, ordered by seq ASC. */
  byType(type: string): EventRow[] {
    return this.stmtByType.all({ type });
  }

  /** Return events filtered by step (and optionally type), ordered by seq ASC. */
  byStep(step: string, type?: string): EventRow[] {
    if (type !== undefined) {
      return this.stmtByStepType.all({ step, type });
    }
    return this.stmtByStep.all({ step });
  }

  /** Return events with seq > the given value, ordered by seq ASC. */
  since(seq: number): EventRow[] {
    return this.stmtSince.all({ seq });
  }

  /** Return the most recent event of the given type, or null if none exist. */
  last(type: string): EventRow | null {
    return this.stmtLast.get({ type });
  }

  /** Return total event count (for diagnostics). */
  eventCount(): number {
    const row = this.stmtCount.get();
    return row?.cnt ?? 0;
  }

  // -------------------------------------------------------------------------
  // Cleanup
  // -------------------------------------------------------------------------

  /** Close the database. Best-effort WAL checkpoint before closing. */
  close(): void {
    try {
      this.db.run('PRAGMA wal_checkpoint(TRUNCATE)');
    } catch {
      // Cleanup is best-effort — ignore errors (e.g., in-memory databases)
    }
    this.db.close();
  }

  /** Auto-cleanup via `using store = new EventStore(path)`. */
  [Symbol.dispose](): void {
    this.close();
  }
}
