/**
 * SQLite event store — typed wrapper around bun:sqlite.
 *
 * All methods are synchronous (bun:sqlite is a synchronous API).
 * Uses WAL mode, cached prepared statements via db.query(), and
 * ON CONFLICT(idempotency_key) DO NOTHING RETURNING * for atomic dedup.
 *
 * Schema v5+ adds explicit `session_id` and `project_id` columns to the
 * `events` table — previously these partition keys were only implicit
 * in the row's `idempotency_key` string. The column-level encoding makes
 * per-session and per-project queries a direct projection rather than a
 * string-parse. See DRIFT-3 in `.claude/project/gobbi/design/v050-features/gobbi-memory/review.md`
 * for the design rationale + backfill semantics (gobbi-memory Pass 2,
 * issue #118). `session_id` is read from the constructor's inferred
 * sessionId (derived from the session directory name); `project_id` is
 * the `basename(projectRoot)` captured from the session's metadata.json.
 */

import { Database } from 'bun:sqlite';
import { readFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import {
  CURRENT_SCHEMA_VERSION,
  backfillSessionAndProjectIds,
  ensureSchemaV5,
} from './migrations.js';
import type { EventRow } from './migrations.js';

// Re-export EventRow for consumers that import from store
export type { EventRow } from './migrations.js';

// ---------------------------------------------------------------------------
// Append input types
// ---------------------------------------------------------------------------

/**
 * Idempotency key formula selector.
 *
 * - 'tool-call': `${sessionId}:${toolCallId}:${eventType}` — for events
 *   triggered by tool calls (guard, delegation).
 * - 'system': `${sessionId}:${timestampMs}:${eventType}` — for events
 *   generated by the system (timeout, one-shot system events).
 * - 'counter': `${sessionId}:${timestampMs}:${eventType}:${counter}` —
 *   for events that may legitimately repeat within the same millisecond
 *   (heartbeats). The caller supplies a monotonically increasing counter
 *   per same-ms collision window so the UNIQUE constraint does not
 *   silently drop repeats.
 */
export type IdempotencyKind = 'tool-call' | 'system' | 'counter';

/**
 * Fields shared across every `AppendInput` variant — excludes `seq`
 * (auto-assigned) and `idempotency_key` (computed from the variant).
 */
interface AppendInputBase {
  readonly ts: string;
  readonly type: string;
  readonly step?: string | null | undefined;
  readonly data?: string | undefined;
  readonly actor: string;
  readonly parent_seq?: number | null | undefined;
  /** Required for every formula — identifies the session. */
  readonly sessionId: string;
}

/** Tool-call variant — `toolCallId` required, formula ignores `ts`. */
export interface AppendInputToolCall extends AppendInputBase {
  readonly idempotencyKind: 'tool-call';
  readonly toolCallId: string;
  readonly counter?: never;
}

/**
 * System variant — formula hashes `(sessionId, ts→ms, type)`. Suitable
 * when at most one event of `type` can fire per session-millisecond.
 */
export interface AppendInputSystem extends AppendInputBase {
  readonly idempotencyKind: 'system';
  readonly toolCallId?: never;
  readonly counter?: never;
}

/**
 * Counter variant — formula hashes `(sessionId, ts→ms, type, counter)`.
 * `counter` is REQUIRED — the discriminated union forces callers to supply
 * it whenever `kind === 'counter'`, so same-ms collisions disambiguate
 * without falling back to the silent-dedup branch of ON CONFLICT.
 */
export interface AppendInputCounter extends AppendInputBase {
  readonly idempotencyKind: 'counter';
  readonly toolCallId?: never;
  readonly counter: number;
}

/**
 * Discriminated union — TypeScript enforces the per-kind fields at
 * construction time. `toolCallId` is only legal when `kind === 'tool-call'`;
 * `counter` is only legal (and is REQUIRED) when `kind === 'counter'`.
 */
export type AppendInput =
  | AppendInputToolCall
  | AppendInputSystem
  | AppendInputCounter;

// ---------------------------------------------------------------------------
// SQLite binding type — compatible with bun:sqlite's SQLQueryBindings
// ---------------------------------------------------------------------------

type SqlBindings = Record<string, string | number | bigint | boolean | null>;

// ---------------------------------------------------------------------------
// SQL statements
// ---------------------------------------------------------------------------

const SQL_CREATE_TABLE = `
CREATE TABLE IF NOT EXISTS events (
  seq INTEGER PRIMARY KEY,
  ts TEXT NOT NULL,
  schema_version INTEGER NOT NULL,
  type TEXT NOT NULL,
  step TEXT,
  data TEXT NOT NULL DEFAULT '{}',
  actor TEXT NOT NULL,
  parent_seq INTEGER REFERENCES events(seq),
  idempotency_key TEXT NOT NULL UNIQUE,
  session_id TEXT,
  project_id TEXT
)`;

const SQL_CREATE_INDEX_TYPE = `
CREATE INDEX IF NOT EXISTS idx_events_type ON events(type)`;

const SQL_CREATE_INDEX_STEP_TYPE = `
CREATE INDEX IF NOT EXISTS idx_events_step_type ON events(step, type)`;

const SQL_APPEND = `
INSERT INTO events (ts, schema_version, type, step, data, actor, parent_seq, idempotency_key, session_id, project_id)
VALUES ($ts, $schema_version, $type, $step, $data, $actor, $parent_seq, $idempotency_key, $session_id, $project_id)
ON CONFLICT(idempotency_key) DO NOTHING
RETURNING *`;

const SQL_REPLAY_ALL = `SELECT * FROM events ORDER BY seq ASC`;

const SQL_BY_TYPE = `SELECT * FROM events WHERE type = $type ORDER BY seq ASC`;

const SQL_BY_STEP = `SELECT * FROM events WHERE step = $step ORDER BY seq ASC`;

const SQL_BY_STEP_TYPE = `SELECT * FROM events WHERE step = $step AND type = $type ORDER BY seq ASC`;

const SQL_SINCE = `SELECT * FROM events WHERE seq > $seq ORDER BY seq ASC`;

const SQL_LAST = `SELECT * FROM events WHERE type = $type ORDER BY seq DESC LIMIT 1`;

const SQL_LAST_N = `SELECT * FROM events WHERE type = $type ORDER BY seq DESC LIMIT $n`;

const SQL_LAST_N_ANY = `SELECT * FROM events ORDER BY seq DESC LIMIT $n`;

const SQL_COUNT = `SELECT count(*) as cnt FROM events`;

/**
 * Cost-rollup SELECT over all `delegation.complete` events, ordered by
 * seq ASC. Powers `gobbi workflow status --cost` aggregation.
 *
 * Hoisted as a module-level `const` so `bun:sqlite`'s prepared-statement
 * cache (keyed by SQL identity) hits across repeated invocations — per
 * research §E.6 innovative override. Co-located with the other SQL
 * constants so reviewers see the full set when auditing the schema.
 *
 * Column shape (one row per `delegation.complete` event):
 *
 *   step           TEXT      — workflow step the delegation ran under
 *   subagentId     TEXT      — delegation's subagent identifier
 *   tokensJson     TEXT      — json_extract of `data.tokensUsed`; a JSON
 *                              string of the `message.usage` object, or
 *                              NULL when the event predates PR E's usage
 *                              pipeline
 *   model          TEXT      — Anthropic model id from `data.model`
 *   bytes          INTEGER   — `data.sizeProxyBytes` — the byte-proxy
 *                              fallback used when tokensJson is NULL
 *
 * Rows with neither tokensJson nor bytes contribute 0 to the rollup.
 */
const SQL_AGGREGATE_DELEGATION_COSTS = `
SELECT
  step                                            AS step,
  json_extract(data, '$.subagentId')              AS subagentId,
  json_extract(data, '$.tokensUsed')              AS tokensJson,
  json_extract(data, '$.model')                   AS model,
  json_extract(data, '$.sizeProxyBytes')          AS bytes
FROM events
WHERE type = 'delegation.complete'
ORDER BY seq ASC
`;

// ---------------------------------------------------------------------------
// Analytics row shapes — exported so callers can narrow via shared types
// rather than redefining the row shape per call site.
// ---------------------------------------------------------------------------

/**
 * Raw row shape produced by {@link EventStore.aggregateDelegationCosts}.
 *
 * Every field is nullable because `json_extract` returns NULL for missing
 * paths. Callers narrow each field with `lib/guards.ts` before use — the
 * generic return type is a typed hint, not runtime validation.
 */
export interface CostAggregateRow {
  readonly step: string | null;
  readonly subagentId: string | null;
  readonly tokensJson: string | null;
  readonly model: string | null;
  readonly bytes: number | null;
}

// ---------------------------------------------------------------------------
// Structural read/write interface split
// ---------------------------------------------------------------------------

/**
 * Read-only facet of the event store. Every callable on this interface is a
 * pure query — no INSERT, no transaction boundary, no close. Call sites that
 * only ever read (prompt compilers, pathway detector, cost rollup, state
 * derivation) accept this narrow interface so TypeScript rejects accidental
 * writes at compile time.
 *
 * This is the structural (type-level) evolution of what was previously an
 * advisory "read vs. write" convention in the class docblock. The runtime
 * class is unchanged — `EventStore` still exposes both facets — but the
 * declared contract at a callee's boundary now tightens what that callee
 * can legally do with its `store` parameter.
 *
 * To extend: add a new pure-query method signature here AND on the
 * `EventStore` class body. The class `implements WriteStore` clause (which
 * extends this interface) closes the loop — adding a query to `ReadStore`
 * without implementing it on the class is a `tsc` error at the class
 * declaration, not at the call site.
 */
export interface ReadStore {
  replayAll(): EventRow[];
  byType(type: string): EventRow[];
  byStep(step: string, type?: string): EventRow[];
  since(seq: number): EventRow[];
  last(type: string): EventRow | null;
  lastN(type: string, n: number): readonly EventRow[];
  lastNAny(n: number): readonly EventRow[];
  eventCount(): number;
  aggregateDelegationCosts(): readonly CostAggregateRow[];
}

/**
 * Full read+write facet of the event store. Extends {@link ReadStore} with
 * the mutating operations (`append`, `transaction`) and the lifecycle
 * method (`close`). Call sites that mutate the store — the engine's
 * `appendEventAndUpdateState`, the CLI command handlers that construct and
 * tear down the database, the verification runner — keep this wider type.
 *
 * Callers SHOULD prefer the narrowest interface that covers their needs:
 * `ReadStore` for pure queries, `WriteStore` for anything else. `EventStore`
 * itself remains the concrete construction type — `new EventStore(path)`
 * returns a value usable as either interface.
 */
export interface WriteStore extends ReadStore {
  append(input: AppendInput): EventRow | null;
  transaction<T>(fn: () => T): T;
  close(): void;
}

// ---------------------------------------------------------------------------
// Partition-key resolution helpers — used by the EventStore constructor
// to derive `session_id` + `project_id` from on-disk layout.
// ---------------------------------------------------------------------------

/**
 * Resolve the session id from the directory that contains `gobbi.db`.
 * The session id is the directory's basename
 * (`.gobbi/sessions/<sessionId>/gobbi.db`). Returns `null` when the
 * directory is null (in-memory store) or when the basename resolves to
 * an empty string (filesystem root).
 */
function resolveSessionId(sessionDir: string | null): string | null {
  if (sessionDir === null) return null;
  const name = basename(sessionDir);
  return name === '' ? null : name;
}

/**
 * Resolve `basename(projectRoot)` from the session's `metadata.json`.
 * Silent on every failure mode (missing file, parse error, unexpected
 * shape) — the project_id column stays NULL until a future open
 * recovers a valid metadata.
 */
function resolveProjectRootBasename(
  sessionDir: string | null,
): string | null {
  if (sessionDir === null) return null;
  let raw: string;
  try {
    raw = readFileSync(join(sessionDir, 'metadata.json'), 'utf8');
  } catch {
    return null;
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    return null;
  }
  const projectRoot = (parsed as Record<string, unknown>)['projectRoot'];
  if (typeof projectRoot !== 'string' || projectRoot === '') return null;
  const name = basename(projectRoot);
  return name === '' ? null : name;
}

// ---------------------------------------------------------------------------
// EventStore class
// ---------------------------------------------------------------------------

export class EventStore implements WriteStore {
  private readonly db: Database;

  /**
   * Session partition key — derived from the session directory name (the
   * parent of the `gobbi.db` file). Populated on every v5 INSERT so the
   * per-session partition is queryable by column rather than by parsing
   * the `idempotency_key` prefix. `null` when the store is opened on
   * `:memory:` or any path where the containing directory is the
   * filesystem root (tests).
   */
  private readonly sessionId: string | null;

  /**
   * Project partition key — `basename(metadata.projectRoot)` read from
   * the session's `metadata.json` at construction. `null` when
   * `metadata.json` is missing, unreadable, or malformed. Populated on
   * every v5 INSERT alongside `session_id`; NULL rows are left alone
   * unless {@link backfillSessionAndProjectIds} stamps them during a
   * later open.
   */
  private readonly projectRootBasename: string | null;

  // Cached prepared statements — db.query() returns cached compiled bytecode.
  // Using SqlBindings as the param type to satisfy bun-types' SQLQueryBindings
  // constraint (requires index signature that named interfaces lack).
  private readonly stmtAppend;
  private readonly stmtReplayAll;
  private readonly stmtByType;
  private readonly stmtByStep;
  private readonly stmtByStepType;
  private readonly stmtSince;
  private readonly stmtLast;
  private readonly stmtLastN;
  private readonly stmtLastNAny;
  private readonly stmtCount;
  private readonly stmtAggregateDelegationCosts;

  constructor(pathOrMemory: string) {
    this.db = new Database(pathOrMemory, { strict: true });
    this.db.run('PRAGMA journal_mode = WAL');
    this.db.run('PRAGMA synchronous = NORMAL');
    this.db.run('PRAGMA foreign_keys = ON');
    this.db.run('PRAGMA busy_timeout = 5000');

    // Resolve partition keys from the db path's session directory. In-memory
    // stores and any path whose parent is the filesystem root get null keys.
    const sessionDir =
      pathOrMemory === ':memory:' ? null : dirname(pathOrMemory);
    this.sessionId = resolveSessionId(sessionDir);
    this.projectRootBasename = resolveProjectRootBasename(sessionDir);

    this.initSchema();
    // v4 → v5 row-level backfill. Idempotent — writes only to rows whose
    // partition keys are NULL (the legacy-v4 shape). Runs outside the
    // SQL_CREATE_TABLE / ALTER path because it depends on the resolved
    // `sessionId` + `projectRootBasename`, which `initSchema` does not
    // know about.
    if (this.sessionId !== null) {
      backfillSessionAndProjectIds(
        this.db,
        this.sessionId,
        this.projectRootBasename,
      );
    }

    // Cache all prepared statements with typed return values
    this.stmtAppend = this.db.query<EventRow, [SqlBindings]>(SQL_APPEND);
    this.stmtReplayAll = this.db.query<EventRow, []>(SQL_REPLAY_ALL);
    this.stmtByType = this.db.query<EventRow, [SqlBindings]>(SQL_BY_TYPE);
    this.stmtByStep = this.db.query<EventRow, [SqlBindings]>(SQL_BY_STEP);
    this.stmtByStepType = this.db.query<EventRow, [SqlBindings]>(SQL_BY_STEP_TYPE);
    this.stmtSince = this.db.query<EventRow, [SqlBindings]>(SQL_SINCE);
    this.stmtLast = this.db.query<EventRow, [SqlBindings]>(SQL_LAST);
    this.stmtLastN = this.db.query<EventRow, [SqlBindings]>(SQL_LAST_N);
    this.stmtLastNAny = this.db.query<EventRow, [SqlBindings]>(SQL_LAST_N_ANY);
    this.stmtCount = this.db.query<{ cnt: number }, []>(SQL_COUNT);
    this.stmtAggregateDelegationCosts = this.db.query<CostAggregateRow, []>(
      SQL_AGGREGATE_DELEGATION_COSTS,
    );
  }

  // -------------------------------------------------------------------------
  // Schema initialization
  // -------------------------------------------------------------------------

  private initSchema(): void {
    this.db.run(SQL_CREATE_TABLE);
    this.db.run(SQL_CREATE_INDEX_TYPE);
    this.db.run(SQL_CREATE_INDEX_STEP_TYPE);
    // Additive v4 → v5 column migration — no-op when the CREATE TABLE
    // above already emitted the columns on a fresh database. When the
    // store opens an existing pre-v5 file, the ALTER statements inside
    // `ensureSchemaV5` add the columns without data loss.
    ensureSchemaV5(this.db);
  }

  // -------------------------------------------------------------------------
  // Idempotency key computation
  // -------------------------------------------------------------------------

  private static computeIdempotencyKey(input: AppendInput): string {
    switch (input.idempotencyKind) {
      case 'tool-call': {
        // The discriminated-union type already narrows `toolCallId` to
        // `string` here, so the runtime guard is defensive-only — it
        // catches callers that cast through `unknown` to bypass tsc.
        if (input.toolCallId === undefined) {
          throw new Error(
            'toolCallId is required for tool-call idempotency kind',
          );
        }
        return `${input.sessionId}:${input.toolCallId}:${input.type}`;
      }
      case 'system': {
        const timestampMs = Date.parse(input.ts);
        return `${input.sessionId}:${timestampMs}:${input.type}`;
      }
      case 'counter': {
        const timestampMs = Date.parse(input.ts);
        return `${input.sessionId}:${timestampMs}:${input.type}:${input.counter}`;
      }
    }
  }

  // -------------------------------------------------------------------------
  // Write operations
  // -------------------------------------------------------------------------

  /**
   * Append an event to the store.
   *
   * Returns the persisted EventRow with assigned seq, or null if the event
   * was deduplicated (idempotency key already exists).
   *
   * Uses ON CONFLICT(idempotency_key) DO NOTHING RETURNING * — other
   * constraint violations (NOT NULL, FK) still throw.
   */
  append(input: AppendInput): EventRow | null {
    const idempotencyKey = EventStore.computeIdempotencyKey(input);
    // With strict: true, bun:sqlite binds by name WITHOUT the $ prefix.
    // Schema v5 stamps `session_id` + `project_id` explicitly. The
    // constructor-resolved `sessionId` falls back to the input's
    // `sessionId` when a store opened on `:memory:` (no session directory
    // to infer from) still needs to author rows for a specific session
    // during tests.
    const params: SqlBindings = {
      ts: input.ts,
      schema_version: CURRENT_SCHEMA_VERSION,
      type: input.type,
      step: input.step ?? null,
      data: input.data ?? '{}',
      actor: input.actor,
      parent_seq: input.parent_seq ?? null,
      idempotency_key: idempotencyKey,
      session_id: this.sessionId ?? input.sessionId,
      project_id: this.projectRootBasename,
    };
    return this.stmtAppend.get(params);
  }

  /**
   * Wrap a function in a SQLite transaction with IMMEDIATE locking.
   *
   * Acquires a RESERVED lock at BEGIN, failing fast on contention rather
   * than mid-transaction. Nested calls become SAVEPOINTs automatically.
   */
  transaction<T>(fn: () => T): T {
    return this.db.transaction(fn).immediate();
  }

  // -------------------------------------------------------------------------
  // Read operations
  // -------------------------------------------------------------------------

  /** Replay all events ordered by seq ASC. */
  replayAll(): EventRow[] {
    return this.stmtReplayAll.all();
  }

  /** Return events filtered by type, ordered by seq ASC. */
  byType(type: string): EventRow[] {
    return this.stmtByType.all({ type });
  }

  /** Return events filtered by step (and optionally type), ordered by seq ASC. */
  byStep(step: string, type?: string): EventRow[] {
    if (type !== undefined) {
      return this.stmtByStepType.all({ step, type });
    }
    return this.stmtByStep.all({ step });
  }

  /** Return events with seq > the given value, ordered by seq ASC. */
  since(seq: number): EventRow[] {
    return this.stmtSince.all({ seq });
  }

  /** Return the most recent event of the given type, or null if none exist. */
  last(type: string): EventRow | null {
    return this.stmtLast.get({ type });
  }

  /**
   * Return the `n` most recent events of the given type, ordered by seq
   * DESC (newest first). Used by hot-path scans that only care about
   * the tail — e.g. `gobbi workflow stop` walks same-millisecond
   * heartbeats to pick a non-colliding counter and bails out as soon
   * as the millisecond bucket changes.
   *
   * Bounded by `n` at the SQL layer — the caller never materialises
   * the full `type` history. `n` must be positive; a non-positive
   * value returns an empty array (matches SQLite's LIMIT semantics).
   */
  lastN(type: string, n: number): readonly EventRow[] {
    if (n <= 0) return [];
    return this.stmtLastN.all({ type, n });
  }

  /**
   * Return the `n` most recent events regardless of type, ordered by seq
   * DESC (newest first). Used by PR D's `detectPathway` Crash branch to
   * collect the last handful of event seqs for operator-briefing context.
   *
   * Bounded by `n` at the SQL layer; `n <= 0` returns an empty array
   * (matches `lastN`'s non-positive-input contract).
   */
  lastNAny(n: number): readonly EventRow[] {
    if (n <= 0) return [];
    return this.stmtLastNAny.all({ n });
  }

  /** Return total event count (for diagnostics). */
  eventCount(): number {
    const row = this.stmtCount.get();
    return row?.cnt ?? 0;
  }

  /**
   * Aggregate all `delegation.complete` events into cost-rollup rows
   * ordered by seq ASC. Powers `gobbi workflow status --cost`.
   *
   * The SQL constant lives in this module (not at the call site) so the
   * query surface on `EventStore` stays named and reviewable — every new
   * analytics command adds a named method here rather than threading raw
   * SQL through the public API. The cached prepared statement keeps
   * bun:sqlite's SQL-identity cache hit across repeated invocations.
   *
   * Rows are typed as {@link CostAggregateRow} (every field nullable
   * because `json_extract` returns NULL for missing paths). Callers
   * narrow each field via `lib/guards.ts` before use — the typing is a
   * convenience hint, not runtime validation.
   *
   * Scope: read-only. New analytics queries should be added as sibling
   * named methods on `EventStore` rather than re-introducing a generic
   * raw-SQL surface.
   */
  aggregateDelegationCosts(): readonly CostAggregateRow[] {
    return this.stmtAggregateDelegationCosts.all();
  }

  // -------------------------------------------------------------------------
  // Cleanup
  // -------------------------------------------------------------------------

  /** Close the database. Best-effort WAL checkpoint before closing. */
  close(): void {
    try {
      this.db.run('PRAGMA wal_checkpoint(TRUNCATE)');
    } catch {
      // Cleanup is best-effort — ignore errors (e.g., in-memory databases)
    }
    this.db.close();
  }

  /** Auto-cleanup via `using store = new EventStore(path)`. */
  [Symbol.dispose](): void {
    this.close();
  }
}
